### ISSUE TITLE
"Sticky" Go/No-Go Buttons

### ISSUE THREAD

**Issue by AndyM84** [AndyM84/go-no-go#1]
Need to have the UI Go/No-Go buttons 'stick' to whichever state you select.  Probably need to have them be one way or the other by default, but not sure which direction we should go there yet.

**Comment by mogosilva** [comment]
Figured out how to do this in blueprint. Refer to PlayerUI widget blueprint's event graph for the OnClicked (GO_button)

![gonogo_buttonstickexampleblueprint](https://cloud.githubusercontent.com/assets/11721392/7194794/b75628ee-e483-11e4-883f-0e988b76d39d.JPG)
